language: c

# safelist
branches:
  only:
  - master

before_install:
- git clone -b devel --depth 1 git://github.com/nim-lang/Nim.git
- cd Nim
- git clone --depth 1 git://github.com/nim-lang/csources
- cd csources && sh build.sh
- cd ..
- bin/nim c koch
- "./koch boot -d:release"
- "./koch nimble"
- export PATH=$PWD/bin:$PATH
- cd ..
script:
- nim c -d:release src/vkbot.nim